const $=s=>document.querySelector(s),K='forgecodex_keys_v1';
let hist=[],currentSha='';
function settings(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}}
function saveSettings(){localStorage.setItem(K,JSON.stringify({or:$('#or').value.trim(),gh:$('#gh').value.trim(),model:$('#model').value||'z-ai/glm-5.2:free'}));setStatus('Settings saved');loadRepos().catch(showErr)}
function setStatus(t){$('#status').textContent=t}
function showErr(e){setStatus('Error');add('err','Error: '+(e?.message||e))}
function add(c,t){const x=document.createElement('div');x.className='msg '+c;x.textContent=t;$('#chat').append(x);x.scrollIntoView({block:'end'})}
async function gh(path,opt={}){const k=settings();if(!k.gh)throw Error('GitHub token required');const h={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${k.gh}`,...(opt.headers||{})};if(opt.body)h['Content-Type']='application/json';const r=await fetch('https://api.github.com'+path,{...opt,headers:h});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||`GitHub ${r.status}`);return d}
async function orChat(messages,tools){const k=settings();if(!k.or)throw Error('OpenRouter key required');const model=k.model||'z-ai/glm-5.2:free';const body={model,messages,tools,tool_choice:'auto'};if(model.startsWith('z-ai/glm-5.2'))body.reasoning={effort:'high'};const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${k.or}`,'Content-Type':'application/json','HTTP-Referer':location.origin,'X-Title':'ForgeCodex'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||`OpenRouter ${r.status}`);return d}
function active(){const v=$('#repo').value||'';const i=v.indexOf('/');return{owner:v.slice(0,i),repo:v.slice(i+1),ref:$('#branch').value||'main'}}
async function loadRepos(){setStatus('Loading repos…');const d=await gh('/user/repos?per_page=100&sort=updated&affiliation=owner,collaborator,organization_member');$('#repo').innerHTML=d.map(x=>`<option>${x.full_name}</option>`).join('');await loadBranches();setStatus('Ready · '+modelLabel())}
async function loadBranches(){const r=active();if(!r.owner)return;const d=await gh(`/repos/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}/branches?per_page=100`);$('#branch').innerHTML=d.map(x=>`<option>${x.name}</option>`).join('')}
function modelLabel(){const m=settings().model||'z-ai/glm-5.2:free';return m==='z-ai/glm-5.2:free'?'GLM-5.2 Free':m==='z-ai/glm-5.2'?'GLM-5.2':'GLM-5.3 Flash'}
const b64enc=s=>btoa(unescape(encodeURIComponent(s))),b64dec=s=>decodeURIComponent(escape(atob((s||'').replace(/\n/g,''))));
async function getFile(path,ref){const r=active();return gh(`/repos/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}/contents/${path.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(ref||r.ref)}`)}
async function writeFile(path,content,message,branch){const r=active();let old=null;try{old=await getFile(path,branch||r.ref)}catch{}const body={message:message||`Update ${path} via ForgeCodex`,content:b64enc(content),branch:branch||r.ref};if(old?.sha)body.sha=old.sha;return gh(`/repos/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}/contents/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'PUT',body:JSON.stringify(body)})}
async function listTree(ref){const r=active();return gh(`/repos/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}/git/trees/${encodeURIComponent(ref||r.ref)}?recursive=1`)}
async function createBranch(name,from){const r=active();const s=await gh(`/repos/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}/git/ref/heads/${encodeURIComponent(from||r.ref)}`);return gh(`/repos/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}/git/refs`,{method:'POST',body:JSON.stringify({ref:`refs/heads/${name}`,sha:s.object.sha})})}
async function createPR(title,head,base='main',body=''){const r=active();return gh(`/repos/${encodeURIComponent(r.owner)}/${encodeURIComponent(r.repo)}/pulls`,{method:'POST',body:JSON.stringify({title,head,base,body})})}
const tools=[
{type:'function',function:{name:'list_tree',description:'List repository files recursively',parameters:{type:'object',properties:{ref:{type:'string'}}}}},
{type:'function',function:{name:'read_file',description:'Read a repository text file',parameters:{type:'object',properties:{path:{type:'string'},ref:{type:'string'}},required:['path']}}},
{type:'function',function:{name:'write_file',description:'Create or update a text file and commit it',parameters:{type:'object',properties:{path:{type:'string'},content:{type:'string'},message:{type:'string'},branch:{type:'string'}},required:['path','content']}}},
{type:'function',function:{name:'create_branch',description:'Create a Git branch',parameters:{type:'object',properties:{branch:{type:'string'},from:{type:'string'}},required:['branch']}}},
{type:'function',function:{name:'create_pr',description:'Create a pull request',parameters:{type:'object',properties:{title:{type:'string'},head:{type:'string'},base:{type:'string'},body:{type:'string'}},required:['title','head']}}}
];
async function tool(name,a){if(name==='list_tree'){const d=await listTree(a.ref);return{tree:(d.tree||[]).filter(x=>x.type==='blob').slice(0,3000).map(x=>x.path),truncated:d.truncated}}if(name==='read_file'){const d=await getFile(a.path,a.ref);return{path:a.path,sha:d.sha,content:b64dec(d.content)}}if(name==='write_file'){const d=await writeFile(a.path,a.content,a.message,a.branch);return{commit:d.commit?.sha,content:d.content?.sha,path:a.path}}if(name==='create_branch'){const d=await createBranch(a.branch,a.from);return{ref:d.ref,sha:d.object?.sha}}if(name==='create_pr'){const d=await createPR(a.title,a.head,a.base,a.body);return{number:d.number,url:d.html_url,title:d.title}}return{error:'unknown tool'}}
async function runAgent(text){const r=active();let msgs=[{role:'system',content:`You are ForgeCodex, a careful coding agent operating directly on GitHub from an iPad browser. Current repository: ${r.owner}/${r.repo}, branch: ${r.ref}. Inspect files before editing. Make minimal, coherent changes. For substantial changes prefer creating a branch and PR. You have no shell, terminal, build runner, filesystem outside GitHub, or test execution. Never claim a build/test ran unless evidence is present in repository data.`},...hist,{role:'user',content:text}];for(let i=0;i<12;i++){setStatus(`${modelLabel()} · Agent ${i+1}/12`);const d=await orChat(msgs,tools);const m=d.choices?.[0]?.message;if(!m)throw Error('No model response');msgs.push(m);if(!m.tool_calls?.length){hist.push({role:'user',content:text},{role:'assistant',content:m.content||''});setStatus('Ready · '+modelLabel());return m.content||''}for(const c of m.tool_calls){let a={};try{a=JSON.parse(c.function.arguments||'{}')}catch{}let out;try{out=await tool(c.function.name,a)}catch(e){out={error:e.message}}msgs.push({role:'tool',tool_call_id:c.id,name:c.function.name,content:JSON.stringify(out).slice(0,90000)})}}throw Error('Agent step limit reached')}
$('#save').onclick=saveSettings;$('#model').onchange=()=>{const k=settings();k.model=$('#model').value;localStorage.setItem(K,JSON.stringify(k));setStatus('Ready · '+modelLabel())};$('#repo').onchange=()=>loadBranches().catch(showErr);$('#reload').onclick=()=>loadRepos().catch(showErr);
$('#send').onclick=async()=>{const t=$('#prompt').value.trim();if(!t)return;$('#prompt').value='';add('u',t);$('#send').disabled=true;try{add('a',await runAgent(t))}catch(e){showErr(e)}finally{$('#send').disabled=false}};
$('#clear').onclick=()=>{hist=[];$('#chat').innerHTML=''};
$('#open').onclick=async()=>{try{const d=await getFile($('#path').value.trim());currentSha=d.sha;$('#editor').value=b64dec(d.content);setStatus('File opened')}catch(e){showErr(e)}};
$('#commit').onclick=async()=>{try{await writeFile($('#path').value.trim(),$('#editor').value,$('#msg').value.trim());setStatus('Committed')}catch(e){showErr(e)}};
$('#branchCreate').onclick=async()=>{try{const n=$('#newBranch').value.trim();await createBranch(n);await loadBranches();$('#branch').value=n;$('#gitout').textContent='Created '+n}catch(e){showErr(e)}};
$('#prCreate').onclick=async()=>{try{const title=$('#prTitle').value.trim()||'ForgeCodex changes';const d=await createPR(title,$('#branch').value,'main','Created from ForgeCodex iPad');$('#gitout').textContent=d.html_url}catch(e){showErr(e)}};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');['chat','files','github'].forEach(x=>$('#'+x+'Tab').classList.toggle('hidden',x!==b.dataset.tab))});
(()=>{const k=settings();$('#or').value=k.or||'';$('#gh').value=k.gh||'';$('#model').value=k.model||'z-ai/glm-5.2:free';if(k.gh)loadRepos().catch(showErr);else setStatus('Enter keys · '+modelLabel())})();
